name: trigger on filtered tag

on:
  pull_request_target:
  push:

jobs:
  do-some-PR-thing:
    runs-on: ubuntu-latest
    steps:
      - name: BEFORE checkout
        run: |
          env | grep ^GITHUB
      - name: Checkout
        uses: actions/checkout@v4
      - name: AFTER checkout
        run: |
          env | grep ^GITHUB
          $GITHUB_WORKSPACE/helloworld.sh
          echo "this was AFTER checkout"
      - name: PR thing
        run: echo "Awesome PR"
