name: push-approval

on:
  push:

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: approve-pr
        run: |
          gh pr review --approve 10
        env:
          GH_TOKEN: ${{ github.token }}
