name: Context testing
on:
  pull_request_review:
    types: [submitted]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: PR review commit ID
        id: cid
        run: |
          echo "Review comment: ${{ github.event.review.body }}"
          echo "Reviewed commit: ${{ github.event.review.commit_id }}"
          echo "sha=${{ github.event.review.commit_id }}" >> $GITHUB_OUTPUT
      - name: Target commit
        run: |
          echo ${{ steps.cid.outputs.sha }}
      #      - name: (PR review) Checkout review SHA
      #        uses: actions/checkout@v3
      #        with:
      #          ref: ${{ steps.cid.outputs.sha }}
      #      - name: Print content
      #        run: |
      #          cat foo
      - name: (PR review) Checkout review SHA directly
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.review.commit_id }}
      - name: Print content from commit_id
        run: |
          cat foo
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
